project:
  type: book
  output-dir: docs
book:
  title: "Statistical Inference For Data Science"
  author: "Saul Diaz Infante Velasco"
  search: true
  cover-image: cover.png
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  date: "2/23/2023"
  repo-url: https://github.com/SaulDiazInfante/statisticalInferenceinR4DS   
  repo-actions: [edit]
  sidebar:
    style: docked
    background: light
    collapse-level: 3
    pinned: true
  favicon: cover1.png
  twitter-card: true
  site-url: https://www.saul-diaz-infante-velasco.com
  chapters:
    - index.qmd
    - intro.qmd
    - part: background_00.qmd
      chapters:
        - r_fundamentals_for_data_science.qmd
        - _introduction_to_r_01.qmd
        - _introduction_to_r_02.qmd
        - _introduction_to_r_03.qmd
        - _introduction_to_r_04.qmd
        - _introduction_to_r_05.qmd
        - _introduction_to_r_06.qmd
    - part: background_01.qmd
      chapters:
        - _intermediate_r_01.qmd
        - _intermediate_r_02.qmd
        - _intermediate_r_03.qmd
        - _intermediate_r_04.qmd
        - _intermediate_r_05.qmd
        - data_visualization.qmd
    - part: background_02.qmd
      chapters:
        - _writing_functions_01.qmd
        - data_visualization.qmd
    - part: background_03.qmd
      chapters:
        - _introduction_to_importing_data_in_R_01.qmd
        - _introduction_to_importing_data_in_R_02.qmd
        - _introduction_to_importing_data_in_R_03.qmd
        - _introduction_to_importing_data_in_R_04.qmd
        - _intermediate_importing_data_in_R_01.qmd
        - _intermediate_importing_data_in_R_02.qmd
        - _intermediate_importing_data_in_R_03.qmd
        - _intermediate_importing_data_in_R_04.qmd
        - _intermediate_importing_data_in_R_05.qmd
        - _cleaning_data_in_R_01.qmd
        - _cleaning_data_in_R_02.qmd
        - _cleaning_data_in_R_03.qmd
        - _cleaning_data_in_R_04.qmd
        - _reshaping_data_with_tidyr_01.qmd
        - _reshaping_data_with_tidyr_02.qmd
        - _reshaping_data_with_tidyr_03.qmd
        - _reshaping_data_with_tidyr_04.qmd
    - part: statistical-inference-whole-game.qmd
      chapters:
        - statistical_inference.qmd
        - linear_regression.qmd
        # Bootstrap
        # Permutaion methods
    - summary.qmd
    - references.qmd
  
bibliography: references.bib
csl: elsevier-with-titles-alphabetical.csl

format:
  html:
    theme:
      light: flatly
      dark: darkly
    fig-width: 8
    fig-height: 4
    code-fold: true
    code-tools: true
    code-link: true

pdf:
  documentclass: scrreprt
epub:
  cover-image: cover.png
jupyter: python3
execute:
  echo: false


