# Nuts and bolts: Data types {.unnumbered}

## Entering Input: the assigment operator {.unnumbered}

The thing that we type on the R console prompt are expressions. The firs 
expression we discuses here is the assignment operator, please watch the 
following video <https://www.youtube.com/watch?v=vGY5i_J2c-c&t=283s>

{{< include _atomic_objects.qmd >}} 

{{< include _introduction_to_r_01.qmd >}}

{{< include _introduction_to_r_02.qmd >}}

{{< include _introduction_to_r_03.qmd >}}

{{< include _introduction_to_r_04.qmd >}}

{{< include _introduction_to_r_05.qmd >}}

{{< include _introduction_to_r_06.qmd >}}

# Relational and logical operators, and conditional statements.{.unnumberd} 

{{< include _intermediate_r_01.qmd >}}
# Loops

{{< include _intermediate_r_02.qmd >}}
# Best Coding Practices for R

## What we mean when say "better coding practice"

{{< include _best_coding_practices.qmd >}}

## Folder Structure

## Code Structure

## Sections

## Structural Composition

## Identation

## Styling

## Final Comments

# Tidyverse Fundamentals with R {.unnumbered}

## Introduction to Tidyverse

## Reshaping Data with tidyr

## Project

## Modeling with Data in the Tidyverse

## Communication with Data in the Tidyverse

## Categorical Data in the Tydiverse

# Data Manipulation {.unnumbered}

## Data Manipulation with dplyr

## Joining Data with dplyr

## Case Study: Exploratory Data Analysis in R

## Data Manipulation with data.table in R

## Joining Data with data.table in R
