project:
  type: book
book:
  title: "Introduction to writing functions in R"
  author: "Saul Diaz Infante Velasco"
  date: "2/22/2023"
  search: true
  cover-image: cover.png
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  repo-url: https://github.com/SaulDiazInfante/statisticalInferenceinR4DS   
  repo-actions: [edit]
  sidebar:
    style: docked
    background: light
    collapse-level: 3
    pinned: true
  favicon: cover1.png
  twitter-card: true
  site-url: https://www.saul-diaz-infante-velasco.com

  chapters:
    - index.qmd
    - intro.qmd
    - _writing_functions_01.qmd
    - _writing_functions_02.qmd
    - _writing_functions_03.qmd
    - _writing_functions_04.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: flatly
      dark: cyborg
  pdf:
    documentclass: scrreprt



