project:
  type: book
  output-dir: docs
book:
  title: "Resping Data with tidyr"
  author: "Saul Diaz Infante Velasco"
  search: true
  cover-image: cover.png
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  date: "03/16/2023"
  repo-url: https://github.com/SaulDiazInfante/statisticalInferenceinR4DS   
  repo-actions: [edit]
  sidebar:
    style: docked
    background: light
    collapse-level: 3
    pinned: true
  favicon: cover1.png
  twitter-card: true
  site-url: https://www.saul-diaz-infante-velasco.com
  chapters:
    - index.qmd
    - intro.qmd
    - _reshaping_data_with_tidyr_01.qmd
    - _reshaping_data_with_tidyr_02.qmd
    - _reshaping_data_with_tidyr_03.qmd
    - _reshaping_data_with_tidyr_04.qmd
    - summary.qmd
    - references.qmd
bibliography: references.bib
csl: elsevier-with-titles-alphabetical.csl

format:
  html:
    theme: darkly
    fig-width: 8
    fig-height: 4
    code-fold: true
    code-tools: true
    code-link: true

  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png
jupyter: python3

execute:
  echo: true


