project:
  type: book
  output-dir: docs
book:
  title: "Cleaning Data in R"
  author: "Saul Diaz Infante Velasco"
  search: true
  cover-image: cover.png
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  date: "2/23/2023"
  repo-url: https://github.com/SaulDiazInfante/statisticalInferenceinR4DS   
  repo-actions: [edit]
  sidebar:
    style: docked
    background: light
    collapse-level: 3
    pinned: true
  favicon: cover1.png
  twitter-card: true
  site-url: https://www.saul-diaz-infante-velasco.com
  chapters:
    - index.qmd
    - intro.qmd
    - _cleaning_data_in_R_01.qmd
    - _cleaning_data_in_R_02.qmd
    - _cleaning_data_in_R_03.qmd
    - _cleaning_data_in_R_04.qmd

bibliography: references.bib
format:
  html:
    theme: darkly
    fig-width: 8
    fig-height: 4
    code-fold: true
    code-tools: true
    code-link: true

  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png

execute:
  echo: false


