project:
  type: book

book:
  title: "IntermediateR"
  author: "Saul Díaz Infante Velasco"
  date: "2/8/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - intermediate_r_ch_01.qmd
    - intermediate_r_ch_02.qmd
    - intermediate_r_ch_03.qmd
    - intermediate_r_ch_04.qmd
    - intermediate_r_ch_05.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: darkly
    code-link: true
  pdf:
    documentclass: scrreprt



