---
execute:
  echo: false
format:
  html: 
    theme: darkly
    fig-width: 8
    fig-height: 4
    code-fold: true
    code-link: true
    highlight-style: dracula
    code-line-numbers: true
    code-block-border-left: true
    code-tools:
      source: true
      toggle: false
      caption: none
---
# Introduction {.unnumbered} 

# Grade Rubric {.unnumbered} 
The course encloenses 81 excercise and 14 videos that results in 6950 xp.
```{r}
ch_1_name <- "Conditionals and Control Flow"
ex_names_chapter_1 <- c(
    "Equality",
    "Greater and less than",
    "Compare Vectors",
    "Compare Matrices",
    "& and |",
    "& and | (2)",
    "Blend it all together",
    "The is statement",
    "Add and else",
    "Customize furhter: else if",
    "Take Control"
)
xp_ch_1 <- rep(100, length(ex_names_chapter_1))
df_ch01 <- data.frame(ex_names_chapter_1, xp_ch_1)
names(df_ch01) <- c(
    "name", 
    "XP"
)
# print(df_ch01)
write.csv2(df_ch01, "ch_01.csv")
knitr::kable(df_ch01, format="markdown")
``` 
```{r}
ch_2_name <- "Loops"
ex_names_chapter_2 <- c(
    "Write a while loop",
    "Throw in more conditionals",
    "Stop the while loop: break",
    "Build a while loop from scratch",
    "Loop over a vector",
    "Loop over a list",
    "Loop over a matrix",
    "Mix it up with control flow",
    "Next, you break it",
    "Build a for loop from scratch"
)
xp_ch_2 <- rep(100, length(ex_names_chapter_2))
df_ch02 <- data.frame(ex_names_chapter_2, xp_ch_2)
names(df_ch02) <- c(
    "name", 
    "XP"
)
# print(df_ch01)
write.csv2(df_ch02, "ch_02.csv")
knitr::kable(df_ch02, format="markdown")
```

```{r}
ch_3_name <- "Functions"
ex_names_chapter_3 <- c(
    "Function Documentation",
    "Use a function",
    "Use a function (2)",
    "Use a function (3)",
    "Functions inside functions",
    "Write your own function",
    "Write your own function (2)",
    "Write your own function (3)"
)
xp_ch_3 <- rep(100, length(ex_names_chapter_3))
df_ch03 <- data.frame(ex_names_chapter_3, xp_ch_3)
names(df_ch03) <- c(
    "name", 
    "XP"
)
# print(df_ch01)
write.csv2(df_ch03, "ch_03.csv")
knitr::kable(df_ch03, format="markdown")
```